import { SVGProps } from "../../../core/domain";

const heroListUpDown: SVGProps[] = [
  {
    icon: "triangle",
    hiddenMobile: true,
    width: 48,
    stroke: true,
    color: "icon_orange",
    left: "5%",
    top: "20%",
  },
  {
    icon: "hexa",
    width: 40,
    stroke: true,
    color: "icon_purple",
    left: "60%",
    top: "70%",
  },
  {
    icon: "box",
    width: 6,
    color: "icon_yellow",
    left: "60%",
    top: "15%",
  },
];

const heroListUpDownWide: SVGProps[] = [
  {
    icon: "arrowUp",
    hiddenMobile: true,
    width: 16,
    color: "icon_blue",
    left: "80%",
    top: "10%",
  },
  {
    icon: "triangle",
    width: 12,
    stroke: true,
    color: "icon_brightest",
    left: "90%",
    top: "50%",
  },
  {
    icon: "circle",
    width: 16,
    color: "icon_darker",
    left: "70%",
    top: "95%",
  },
  {
    icon: "triangle",
    width: 16,
    stroke: true,
    color: "icon_darkest",
    left: "30%",
    top: "65%",
  },
  {
    icon: "cross",
    width: 16,
    stroke: true,
    color: "icon_pink",
    left: "28%",
    top: "5%",
  },
  {
    icon: "circle",
    width: 6,
    color: "icon_darkest",
    left: "75%",
    top: "10%",
  },
  {
    icon: "upDown",
    hiddenMobile: true,
    width: 8,
    color: "icon_darkest",
    left: "45%",
    top: "10%",
  },
];

const heroList: SVGProps[] = [
  {
    icon: "circle",
    hiddenMobile: true,
    width: 24,
    color: "icon_darker",
    left: "5%",
    top: "70%",
  },
  {
    icon: "circle",
    width: 6,
    color: "icon_darkest",
    left: "4%",
    top: "20%",
  },
  {
    icon: "circle",
    width: 12,
    color: "icon_darkest",
    left: "50%",
    top: "60%",
  },
  {
    icon: "upDown",
    width: 8,
    color: "icon_darkest",
    left: "95%",
    top: "90%",
  },
  {
    icon: "upDown",
    hiddenMobile: true,
    width: 24,
    color: "icon_darker",
    left: "40%",
    top: "80%",
  },
  {
    icon: "triangle",
    width: 8,
    stroke: true,
    color: "icon_green",
    left: "20%",
    top: "5%",
  },
  {
    icon: "circle",
    width: 64,
    color: "icon_green",
    left: "95%",
    top: "5%",
  },
  {
    icon: "box",
    hiddenMobile: true,
    width: 64,
    color: "icon_green",
    left: "5%",
    top: "90%",
  },
  {
    icon: "box",
    width: 6,
    color: "icon_darkest",
    left: "10%",
    top: "10%",
  },
  {
    icon: "box",
    width: 12,
    color: "icon_darkest",
    left: "40%",
    top: "30%",
  },
  {
    icon: "hexa",
    width: 16,
    stroke: true,
    color: "icon_darker",
    left: "85%",
    top: "40%",
  },
  {
    icon: "hexa",
    width: 8,
    stroke: true,
    color: "icon_darker",
    left: "80%",
    top: "70%",
  },
];

export { heroListUpDown, heroListUpDownWide, heroList };
